/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    print_devices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_print_1devices
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    ls
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_ls
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    cd
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_cd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    pwd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_pwd
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    cp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_cp
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Main
 * Method:    initFS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Main_initFS
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    closeFS
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_closeFS
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
