/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    print_devices
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_print_1devices
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    ls
 * Signature: (Ljava/lang/String;J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Main_ls
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     Main
 * Method:    cd
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_cd
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     Main
 * Method:    pwd
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_pwd
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Main
 * Method:    cp
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_cp
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     Main
 * Method:    initFS
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Main_initFS
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Main
 * Method:    closeFS
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Main_closeFS
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
